<?php declare(strict_types=1);

use FPBlog\Page\InvalidPageException;
use PHPUnit\Framework\TestCase;
use FPBlog\Page\FilePageReader;
use org\bovigo\vfs\vfsStream;

class FilePageReaderTest extends TestCase
{
    protected $path = 'pages';
    protected $file_name = 'page-test';
    protected $content = 'page-test';

    public function setUp(): void
    {
        // setup and cache the virtual file system
        file_put_contents($this->path . DIRECTORY_SEPARATOR . $this->file_name .'.md', $this->content);
    }

    /**
     * @expectedException FPBlog\Page\InvalidPageException
     */
    public function testInvalidPageExceptionIsThrownWhenNoPage(): void
    {
        $file = new FilePageReader('');
        $file->readBySlug('page-no-found.md');
    }

    public function testCanReadBySlug(): void
    {

        $file = new FilePageReader('pages');
        $contentExperted = $file->readBySlug('page-test');

        $this->assertSame($contentExperted, $this->content);
    }

    public function tearDown()
    {
        unlink($this->path . DIRECTORY_SEPARATOR . $this->file_name .'.md');
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

}
